server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://ebfgaommglclml:087fe36058c140f32da602ab7b6c300bc9f7216f4424b1b3800d7082a5127aef@ec2-52-5-247-46.compute-1.amazonaws.com:5432/d8i7cptl9mqc1b
    username: ebfgaommglclml
    password: 087fe36058c140f32da602ab7b6c300bc9f7216f4424b1b3800d7082a5127aef
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander